import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import SessionWrapper from "../components/SessionWrapper";
// import { getServerSession } from "next-auth";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, session }) {

  // const session = await getServerSession();

  return (
    <html lang="en">
    <SessionWrapper session={session}>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </SessionWrapper>
    </html>
  );
}
